### ISSUE TITLE
Razer Phone 2 Calibration

### ISSUE THREAD

**Issue by Cjkeenan** [ezeek/smartly#38]
1.  Calibrated Devices:
![image](https://user-images.githubusercontent.com/10240016/77813096-1d11cb00-7063-11ea-917e-2f105bd5c094.png)

2. Portrait: 
![image](https://user-images.githubusercontent.com/10240016/77813191-db355480-7063-11ea-8281-5880adf9a289.png)
Landscape: 
![image](https://user-images.githubusercontent.com/10240016/77813194-e1c3cc00-7063-11ea-8c90-78297a8b2937.png)

3. https://pastebin.com/4LVBFVeG

4. Portrait: 480x678px, Landscape: 806x400px

**Comment by ezeek** [comment]
Thank you for the report! I've added this device as 'Motorola RAZR2'.  If for some reason it doesn't show up in the auto-complete tag field, you may need to clear your browser cache.

_Note_: currently this new device won't show up under 'FORCE DISPLAY 2 COLUMNS WIDE' because based on the pixel width (over 420px wide) it's assumed the device is too wide to allow for 2 columns wide.  Now that I look at the product itself though, this phone might benefit from allowing forced 2 columns wide.  Please create another issue for this if you feel this device should allow for 'force display 2 columns wide'.  Thanks!

**Comment by Cjkeenan** [comment]
It's not a Motorola RZR2 it's a Razer Phone 2.

**Comment by ezeek** [comment]
rename to "RP2"

**Comment by ezeek** [comment]
Added 'Motorola RP2'.  The progress of having the option to force 2 column wide display will be under this other issue: https://github.com/ezeek/smartly/issues/39

**Comment by Cjkeenan** [comment]
Again it's not a Motorola, it's a Razer product, i.e. the PC gaming guys. https://www2.razer.com/eu-en/mobile/razer-phone-2
